name: Lint and test

on:
  pull_request:
    branches:
    - main
    - cairo-2
  push:
    branches:
    - main
    - cairo-2

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: "0.7.0"

    - name: Cairo lint
      run: scarb fmt --check

    - name: Cairo test
      run: scarb test
